// Code generated by sqlc. DO NOT EDIT.

package model

import (
	"database/sql"
)

type Chat struct {
	ID        int32  `json:"id"`
	SenderID  int32  `json:"sender_id"`
	InboxHash string `json:"inbox_hash"`
	Msg       string `json:"msg"`
	File      string `json:"file"`
	Meta      string `json:"meta"`
	DeletedBy int32  `json:"deleted_by"`
}

type Friend struct {
	ID        int32         `json:"id"`
	UserID    int32         `json:"user_id"`
	FriendID  int32         `json:"friend_id"`
	BlockedBy sql.NullInt32 `json:"blocked_by"`
}

type Inbox struct {
	ID           int32  `json:"id"`
	UserID       int32  `json:"user_id"`
	SenderID     int32  `json:"sender_id"`
	InboxHash    string `json:"inbox_hash"`
	LastMsg      string `json:"last_msg"`
	Seen         bool   `json:"seen"`
	UnseenNumber int32  `json:"unseen_number"`
	Deleted      bool   `json:"deleted"`
}

type User struct {
	ID         int32  `json:"id"`
	FullName   string `json:"full_name"`
	Email      string `json:"email"`
	Password   string `json:"password"`
	ProfilePic string `json:"profile_pic"`
}
