// Code generated by sqlc. DO NOT EDIT.
// source: query.sql

package model

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT id, full_name, email, password, profile_pic FROM "user"
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Password,
		&i.ProfilePic,
	)
	return i, err
}
